version: '3.8'

services:
  webhook-api:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - webhook-db
      - webhook-cache

  webhook-db:
    container_name: webhook-db
    image: postgres
    hostname: localhost
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: webhook-db
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  webhook-cache:
    image: redis:alpine
    container_name: "webhook-cache"
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD:-mySecretPassword}
    volumes:
      - ./redis-data:/data

volumes:
  postgres-data:
  redis-data:


